//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentStore.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreFrontEntities : DbContext
    {
        public StoreFrontEntities()
            : base("name=StoreFrontEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Capacity> Capacities { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<PoleMaterial> PoleMaterials { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<StatusID> StatusIDs { get; set; }
        public virtual DbSet<TentMaterial> TentMaterials { get; set; }
        public virtual DbSet<Tent> Tents { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
