//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentStore.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tent
    {
        public int TentID { get; set; }
        public string Name { get; set; }
        public int BrandID { get; set; }
        public int StatusID { get; set; }
        public int ManufacturerID { get; set; }
        public int DimensionsID { get; set; }
        public int CapacityID { get; set; }
        public int TentMaterialID { get; set; }
        public int PoleMaterialID { get; set; }
        public decimal Price { get; set; }
        public int SeasonID { get; set; }
        public decimal Weight { get; set; }
        public bool isWaterProof { get; set; }
        public bool isDiscontinued { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Capacity Capacity { get; set; }
        public virtual Dimension Dimension { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual PoleMaterial PoleMaterial { get; set; }
        public virtual Season Season { get; set; }
        public virtual StatusID StatusID1 { get; set; }
        public virtual TentMaterial TentMaterial { get; set; }
    }
}
